namespace Bylsan_System.SecurityForm
{
    partial class frmHisotyTrasAction
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn1 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewDateTimeColumn gridViewDateTimeColumn1 = new Telerik.WinControls.UI.GridViewDateTimeColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn2 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn3 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn2 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            this.historyBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.historyRadGridView = new Telerik.WinControls.UI.RadGridView();
            ((System.ComponentModel.ISupportInitialize)(this.historyBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.historyRadGridView)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.historyRadGridView.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
            this.SuspendLayout();
            // 
            // historyBindingSource
            // 
            this.historyBindingSource.DataSource = typeof(XamaDataLayer.History);
            // 
            // historyRadGridView
            // 
            this.historyRadGridView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.historyRadGridView.EnableCustomDrawing = true;
            this.historyRadGridView.EnableCustomFiltering = true;
            this.historyRadGridView.EnableCustomGrouping = true;
            this.historyRadGridView.EnableCustomSorting = true;
            this.historyRadGridView.EnableKeyMap = true;
            this.historyRadGridView.EnableKineticScrolling = true;
            this.historyRadGridView.Location = new System.Drawing.Point(0, 0);
            // 
            // historyRadGridView
            // 
            this.historyRadGridView.MasterTemplate.AllowAddNewRow = false;
            this.historyRadGridView.MasterTemplate.AutoSizeColumnsMode = Telerik.WinControls.UI.GridViewAutoSizeColumnsMode.Fill;
            gridViewDecimalColumn1.DataType = typeof(int);
            gridViewDecimalColumn1.FieldName = "ID";
            gridViewDecimalColumn1.HeaderText = "ID";
            gridViewDecimalColumn1.IsAutoGenerated = true;
            gridViewDecimalColumn1.Name = "ID";
            gridViewDecimalColumn1.Width = 182;
            gridViewTextBoxColumn1.FieldName = "HistoryAction";
            gridViewTextBoxColumn1.HeaderText = "History Action";
            gridViewTextBoxColumn1.IsAutoGenerated = true;
            gridViewTextBoxColumn1.Name = "HistoryAction";
            gridViewTextBoxColumn1.Width = 182;
            gridViewDateTimeColumn1.DataType = typeof(System.Nullable<System.DateTime>);
            gridViewDateTimeColumn1.FieldName = "DateOfProcess";
            gridViewDateTimeColumn1.HeaderText = "Date Of Process";
            gridViewDateTimeColumn1.IsAutoGenerated = true;
            gridViewDateTimeColumn1.Name = "DateOfProcess";
            gridViewDateTimeColumn1.Width = 182;
            gridViewTextBoxColumn2.FieldName = "ActionName";
            gridViewTextBoxColumn2.HeaderText = "Action Name";
            gridViewTextBoxColumn2.IsAutoGenerated = true;
            gridViewTextBoxColumn2.Name = "ActionName";
            gridViewTextBoxColumn2.Width = 182;
            gridViewTextBoxColumn3.FieldName = "Description";
            gridViewTextBoxColumn3.HeaderText = "Description";
            gridViewTextBoxColumn3.IsAutoGenerated = true;
            gridViewTextBoxColumn3.Name = "Description";
            gridViewTextBoxColumn3.Width = 182;
            gridViewDecimalColumn2.DataType = typeof(System.Nullable<int>);
            gridViewDecimalColumn2.FieldName = "UserID";
            gridViewDecimalColumn2.HeaderText = "UserID";
            gridViewDecimalColumn2.IsAutoGenerated = true;
            gridViewDecimalColumn2.Name = "UserID";
            gridViewDecimalColumn2.Width = 181;
            this.historyRadGridView.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewDecimalColumn1,
            gridViewTextBoxColumn1,
            gridViewDateTimeColumn1,
            gridViewTextBoxColumn2,
            gridViewTextBoxColumn3,
            gridViewDecimalColumn2});
            this.historyRadGridView.MasterTemplate.DataSource = this.historyBindingSource;
            this.historyRadGridView.MasterTemplate.EnableCustomFiltering = true;
            this.historyRadGridView.MasterTemplate.EnableCustomGrouping = true;
            this.historyRadGridView.MasterTemplate.EnableCustomSorting = true;
            this.historyRadGridView.MasterTemplate.EnableFiltering = true;
            this.historyRadGridView.MasterTemplate.EnablePaging = true;
            this.historyRadGridView.Name = "historyRadGridView";
            this.historyRadGridView.Size = new System.Drawing.Size(1106, 535);
            this.historyRadGridView.TabIndex = 1;
            this.historyRadGridView.Text = "radGridView1";
            this.historyRadGridView.ThemeName = "Office2010Black";
            // 
            // frmHisotyTrasAction
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1106, 535);
            this.Controls.Add(this.historyRadGridView);
            this.Name = "frmHisotyTrasAction";
            // 
            // 
            // 
            this.RootElement.ApplyShapeToControl = true;
            this.ShowIcon = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "History";
            this.ThemeName = "Office2010Black";
            this.Load += new System.EventHandler(this.frmHisotyTrasAction_Load);
            ((System.ComponentModel.ISupportInitialize)(this.historyBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.historyRadGridView.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.historyRadGridView)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.BindingSource historyBindingSource;
        private Telerik.WinControls.UI.RadGridView historyRadGridView;
    }
}